package libelec;

import static com.sun.javafx.tk.Toolkit.getToolkit;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class Jf_Transporteur extends javax.swing.JFrame {
    Statement stmtTransporteur;
    Connexion maConnexion = new Connexion();
    
    public Jf_Transporteur() {
        initComponents();
        
        //JF à la taille de l'écran
        this.setSize(getToolkit().getScreenSize());
        this.setSize((int)getToolkit().getScreenSize().getWidth(), ((int)getToolkit().getScreenSize().getHeight() - 40));
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        labTransporteur = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabTransporteur = new javax.swing.JTable();
        labNomTransporteur = new javax.swing.JLabel();
        labNumTelFixe = new javax.swing.JLabel();
        labEmail = new javax.swing.JLabel();
        labStatus = new javax.swing.JLabel();
        labNouveauStatus = new javax.swing.JLabel();
        labChampLibre = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtChampLibre = new javax.swing.JTextArea();
        txtNomTransporteur = new javax.swing.JTextField();
        txtNumTelFixe = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        txtStatus = new javax.swing.JTextField();
        txtNouveauStatus = new javax.swing.JTextField();
        butLister = new javax.swing.JButton();
        butModifier = new javax.swing.JButton();
        butAjouter = new javax.swing.JButton();
        butFraisDePort = new javax.swing.JButton();
        butStatus = new javax.swing.JButton();
        butMotsCles = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jDesktopPane1.setBackground(new java.awt.Color(255, 255, 255));
        jDesktopPane1.setForeground(new java.awt.Color(0, 0, 0));

        labTransporteur.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        labTransporteur.setForeground(new java.awt.Color(0, 0, 255));
        labTransporteur.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labTransporteur.setText("TRANSPORTEUR");

        tabTransporteur.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        tabTransporteur.setForeground(new java.awt.Color(0, 0, 0));
        tabTransporteur.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Transporteur", "N° Tel Fixe", "Email", "Status", "Champ Libre"
            }
        ));
        jScrollPane1.setViewportView(tabTransporteur);

        labNomTransporteur.setForeground(new java.awt.Color(0, 0, 255));
        labNomTransporteur.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labNomTransporteur.setText("Transporteur");

        labNumTelFixe.setForeground(new java.awt.Color(0, 0, 255));
        labNumTelFixe.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labNumTelFixe.setText("N° Tel Fixe");

        labEmail.setForeground(new java.awt.Color(0, 0, 255));
        labEmail.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labEmail.setText("Email");

        labStatus.setForeground(new java.awt.Color(0, 0, 255));
        labStatus.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labStatus.setText("Status");

        labNouveauStatus.setForeground(new java.awt.Color(0, 0, 255));
        labNouveauStatus.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labNouveauStatus.setText("Nouveau Status");

        labChampLibre.setForeground(new java.awt.Color(0, 0, 255));
        labChampLibre.setText("Champ Libre");

        txtChampLibre.setColumns(20);
        txtChampLibre.setRows(5);
        jScrollPane2.setViewportView(txtChampLibre);

        butLister.setIcon(new javax.swing.ImageIcon("D:\\librairie\\image\\list.png")); // NOI18N
        butLister.setText("LISTER");
        butLister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butListerActionPerformed(evt);
            }
        });

        butModifier.setIcon(new javax.swing.ImageIcon("D:\\librairie\\image\\ModifierPT.png")); // NOI18N
        butModifier.setText("MODIFIER");
        butModifier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butModifierActionPerformed(evt);
            }
        });

        butAjouter.setIcon(new javax.swing.ImageIcon("D:\\librairie\\image\\add.png")); // NOI18N
        butAjouter.setText("AJOUTER");
        butAjouter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butAjouterActionPerformed(evt);
            }
        });

        butFraisDePort.setText("FRAIS DE PORT");
        butFraisDePort.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butFraisDePortActionPerformed(evt);
            }
        });

        butStatus.setText("STATUS");
        butStatus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butStatusActionPerformed(evt);
            }
        });

        butMotsCles.setText("MOTS CLES");
        butMotsCles.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butMotsClesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jDesktopPane1Layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labNomTransporteur)
                            .addComponent(labNumTelFixe)
                            .addComponent(labEmail)
                            .addComponent(labStatus)
                            .addComponent(labNouveauStatus)
                            .addComponent(labChampLibre))
                        .addGap(24, 24, 24)
                        .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtNumTelFixe, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNomTransporteur, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNouveauStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(34, 34, 34)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jDesktopPane1Layout.createSequentialGroup()
                        .addGap(272, 272, 272)
                        .addComponent(labTransporteur, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jDesktopPane1Layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                                .addGap(24, 24, 24)
                                .addComponent(butFraisDePort, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(butStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(butMotsCles, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                                .addComponent(butLister, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(31, 31, 31)
                                .addComponent(butModifier)
                                .addGap(32, 32, 32)
                                .addComponent(butAjouter)))))
                .addGap(75, 75, 75))
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(labTransporteur)
                .addGap(33, 33, 33)
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jDesktopPane1Layout.createSequentialGroup()
                        .addComponent(txtNomTransporteur, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(179, 179, 179)
                        .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(butAjouter, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(butModifier)
                            .addComponent(butLister))
                        .addGap(60, 60, 60)
                        .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(butFraisDePort, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(butStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(butMotsCles, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jDesktopPane1Layout.createSequentialGroup()
                        .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                                .addGap(3, 3, 3)
                                .addComponent(labNomTransporteur)
                                .addGap(20, 20, 20)
                                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(labNumTelFixe)
                                    .addComponent(txtNumTelFixe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(16, 16, 16)
                                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(labEmail)
                                    .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(9, 9, 9)
                                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(labStatus)
                                    .addComponent(txtStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(16, 16, 16)
                                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(labNouveauStatus)
                                    .addComponent(txtNouveauStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(26, 26, 26)
                        .addComponent(labChampLibre)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(122, 131, Short.MAX_VALUE))
        );
        jDesktopPane1.setLayer(labTransporteur, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jScrollPane1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(labNomTransporteur, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(labNumTelFixe, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(labEmail, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(labStatus, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(labNouveauStatus, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(labChampLibre, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jScrollPane2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(txtNomTransporteur, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(txtNumTelFixe, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(txtEmail, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(txtStatus, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(txtNouveauStatus, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(butLister, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(butModifier, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(butAjouter, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(butFraisDePort, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(butStatus, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(butMotsCles, javax.swing.JLayeredPane.DEFAULT_LAYER);

        getContentPane().add(jDesktopPane1, java.awt.BorderLayout.CENTER);

        setBounds(0, 0, 776, 597);
    }// </editor-fold>//GEN-END:initComponents

    private void butListerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butListerActionPerformed
        // TODO add your handling code here:
        //creation d'un modele
        DefaultTableModel model = new DefaultTableModel();

        //les colonnes
        model.addColumn("Transporteur");
        model.addColumn("N° de Tél");
        model.addColumn("Email");
        model.addColumn("Status");
        model.addColumn("Champ Libre");

        //les lignes
        /*test d'affichage
        model.addRow(new Object[]{"test1","987654","gghf@xgc","1","hdvb"});*/

        //la requette
        String requette = "select * from transporteur";

        try{
            stmtTransporteur = maConnexion.ObtenirConnexion().createStatement();
            ResultSet result = stmtTransporteur.executeQuery(requette);

            while(result.next()){
                model.addRow(new Object[]{result.getString("traNomLivreur"),result.getString("traTelF"),result.getString("traEmail"),result.getString("traStatut"),result.getString("traChampLibre")});
            }

        }
        catch (SQLException ex) {
            System.err.println("Erreur d'exécution de la requette:"+ ex.getErrorCode()+"/"+ ex.getMessage());
        }

        //On applique le modele à la JTable
        tabTransporteur.setModel(model);
    }//GEN-LAST:event_butListerActionPerformed

    private void butModifierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butModifierActionPerformed
        // TODO add your handling code here:
        String nomTransporteur = txtNomTransporteur.getText();
        String nouveauStatut = txtNouveauStatus.getText();
        
        if(nomTransporteur.isEmpty() || nouveauStatut.isEmpty()){
        JOptionPane.showMessageDialog(null, "Veuillez saisir les champs (Transporteur, Nouveau Status)");
    } else{
        
        String requette = "update transporteur set traStatut = ? where traNomLivreur = ?";
        
        try{
            PreparedStatement pstmt = maConnexion.ObtenirConnexion().prepareStatement(requette);
            pstmt.setString(1, nouveauStatut);
            pstmt.setString(2, nomTransporteur);
            pstmt.executeUpdate();
            pstmt.close();
            JOptionPane.showMessageDialog(null, "Le Status du Transporteur est mis à jour");
            
            //vider la table après l'ajout
            txtNomTransporteur.setText("");
            txtNouveauStatus.setText("");
            
        }
        catch(SQLException ex) {
            System.err.println("Erreur d'exécution de la requette:"+ ex.getErrorCode()+"/"+ ex.getMessage());
            
            }
        }
    }//GEN-LAST:event_butModifierActionPerformed

    private void butAjouterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butAjouterActionPerformed
        // TODO add your handling code here:
        String nomTransporteur = txtNomTransporteur.getText();
        String telFixe = txtNumTelFixe.getText();
        String email = txtEmail.getText();
        String status = txtStatus.getText();
        String champLibre = txtChampLibre.getText();
        
        //if(nomTransporteur.length() == 0 || telFixe.length() == 0 || email.length() == 0 || status.length() == 0){
        if(nomTransporteur.isEmpty() || telFixe.isEmpty() || email.isEmpty() || status.isEmpty()){    
        JOptionPane.showMessageDialog(null, "Veuillez saisir les champs (Transporteur, N° Tel Fixe, Email, Status)");
    } else{
        
        String requette = "insert into transporteur (traNomLivreur,traTelF,traEmail,traStatut,traChampLibre) values ('"+nomTransporteur+"','"+telFixe+"','"+email+"','"+status+"','"+champLibre+"')";
                
        try{
            stmtTransporteur = maConnexion.ObtenirConnexion().createStatement();
            stmtTransporteur.executeUpdate(requette);
            JOptionPane.showMessageDialog(null, "Le Transporteur est ajouté");
            
             //vider la table après l'ajout
            txtNomTransporteur.setText("");
            txtNumTelFixe.setText("");
            txtEmail.setText("");
            txtStatus.setText("");
            txtChampLibre.setText("");
            
            }
            catch (SQLException ex) {
            System.err.println("Erreur d'exécution de la requette:"+ ex.getErrorCode()+"/"+ ex.getMessage());
            }
        }
    }//GEN-LAST:event_butAjouterActionPerformed

    private void butFraisDePortActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butFraisDePortActionPerformed
        // TODO add your handling code here:
        Jif_FraisDePort fraisDePort = new Jif_FraisDePort();
        fraisDePort.setVisible(true);
        jDesktopPane1.add(fraisDePort);
        fraisDePort.toFront();
        
    }//GEN-LAST:event_butFraisDePortActionPerformed

    private void butStatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butStatusActionPerformed
        // TODO add your handling code here:
        Jif_Status status = new Jif_Status();
        status.setVisible(true);
        jDesktopPane1.add(status);
        status.toFront();
        
    }//GEN-LAST:event_butStatusActionPerformed

    private void butMotsClesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butMotsClesActionPerformed
        // TODO add your handling code here:
        Jif_MotsCles motsCles = new Jif_MotsCles();
        motsCles.setVisible(true);
        jDesktopPane1.add(motsCles);
        motsCles.toFront();
    }//GEN-LAST:event_butMotsClesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Jf_Transporteur.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Jf_Transporteur.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Jf_Transporteur.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Jf_Transporteur.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Jf_Transporteur().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton butAjouter;
    private javax.swing.JButton butFraisDePort;
    private javax.swing.JButton butLister;
    private javax.swing.JButton butModifier;
    private javax.swing.JButton butMotsCles;
    private javax.swing.JButton butStatus;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel labChampLibre;
    private javax.swing.JLabel labEmail;
    private javax.swing.JLabel labNomTransporteur;
    private javax.swing.JLabel labNouveauStatus;
    private javax.swing.JLabel labNumTelFixe;
    private javax.swing.JLabel labStatus;
    private javax.swing.JLabel labTransporteur;
    private javax.swing.JTable tabTransporteur;
    private javax.swing.JTextArea txtChampLibre;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtNomTransporteur;
    private javax.swing.JTextField txtNouveauStatus;
    private javax.swing.JTextField txtNumTelFixe;
    private javax.swing.JTextField txtStatus;
    // End of variables declaration//GEN-END:variables
}
