package libelec;

import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class Jif_MotsCles extends javax.swing.JInternalFrame {
    Statement stmtMotCle;
    Connexion maConnexion = new Connexion();

    public Jif_MotsCles() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labMotsCles = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabMotsCles = new javax.swing.JTable();
        labMotCle = new javax.swing.JLabel();
        txtMotCle = new javax.swing.JTextField();
        butAjouter = new javax.swing.JButton();
        labMotCleCorrige = new javax.swing.JLabel();
        txtMotCleCorrige = new javax.swing.JTextField();
        butModifier = new javax.swing.JButton();
        butLister = new javax.swing.JButton();
        labMotCleActuel = new javax.swing.JLabel();
        txtMotCleActuel = new javax.swing.JTextField();

        setClosable(true);
        getContentPane().setLayout(null);

        labMotsCles.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        labMotsCles.setForeground(new java.awt.Color(0, 0, 255));
        labMotsCles.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labMotsCles.setText("MOTS CLES");
        getContentPane().add(labMotsCles);
        labMotsCles.setBounds(190, 10, 180, 32);

        tabMotsCles.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        tabMotsCles.setForeground(new java.awt.Color(0, 0, 0));
        tabMotsCles.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mots Cles"
            }
        ));
        jScrollPane1.setViewportView(tabMotsCles);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(290, 50, 190, 220);

        labMotCle.setForeground(new java.awt.Color(0, 0, 255));
        labMotCle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labMotCle.setText("Mot Cle");
        getContentPane().add(labMotCle);
        labMotCle.setBounds(60, 60, 50, 16);
        getContentPane().add(txtMotCle);
        txtMotCle.setBounds(140, 60, 80, 24);

        butAjouter.setIcon(new javax.swing.ImageIcon("D:\\librairie\\image\\add.png")); // NOI18N
        butAjouter.setText("AJOUTER");
        butAjouter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butAjouterActionPerformed(evt);
            }
        });
        getContentPane().add(butAjouter);
        butAjouter.setBounds(70, 110, 130, 48);

        labMotCleCorrige.setForeground(new java.awt.Color(0, 0, 255));
        labMotCleCorrige.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labMotCleCorrige.setText("Mot Cle Corrige");
        getContentPane().add(labMotCleCorrige);
        labMotCleCorrige.setBounds(60, 230, 100, 16);
        getContentPane().add(txtMotCleCorrige);
        txtMotCleCorrige.setBounds(170, 230, 80, 24);

        butModifier.setIcon(new javax.swing.ImageIcon("D:\\librairie\\image\\ModifierPT.png")); // NOI18N
        butModifier.setText("MODIFIER");
        butModifier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butModifierActionPerformed(evt);
            }
        });
        getContentPane().add(butModifier);
        butModifier.setBounds(70, 270, 120, 50);

        butLister.setIcon(new javax.swing.ImageIcon("D:\\librairie\\image\\list.png")); // NOI18N
        butLister.setText("LISTER");
        butLister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butListerActionPerformed(evt);
            }
        });
        getContentPane().add(butLister);
        butLister.setBounds(310, 280, 130, 40);

        labMotCleActuel.setForeground(new java.awt.Color(0, 0, 255));
        labMotCleActuel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labMotCleActuel.setText("Mot Cle Actuel");
        getContentPane().add(labMotCleActuel);
        labMotCleActuel.setBounds(60, 180, 100, 16);
        getContentPane().add(txtMotCleActuel);
        txtMotCleActuel.setBounds(170, 180, 80, 24);

        setBounds(0, 0, 553, 387);
    }// </editor-fold>//GEN-END:initComponents

    private void butAjouterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butAjouterActionPerformed
        // TODO add your handling code here:
        String motcle = txtMotCle.getText();
        
        if(motcle.isEmpty() ){
        JOptionPane.showMessageDialog(null, "Veuillez saisir un mot cle valide");
    } else{
        
        String requette = "insert into motcle (mocLibelle) values ('"+motcle+"')";
        
        try{
            stmtMotCle = maConnexion.ObtenirConnexion().createStatement();
            stmtMotCle.executeUpdate(requette);
            JOptionPane.showMessageDialog(null, "Le Mot Cle est ajouté");
            
            
            //vider la table après l'ajout
            txtMotCle.setText("");
        }
        catch (SQLException ex) {
            System.err.println("Erreur d'exécution de la requette:"+ ex.getErrorCode()+"/"+ ex.getMessage());
            }
        }
    }//GEN-LAST:event_butAjouterActionPerformed

    private void butModifierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butModifierActionPerformed
        // TODO add your handling code here:
        String motCleActuel = txtMotCleActuel.getText();
        String motCleCorrige = txtMotCleCorrige.getText();
        
        if(motCleActuel.isEmpty() || motCleCorrige.isEmpty() ){
        JOptionPane.showMessageDialog(null, "Vous n'avez saisi aucun mot");
    } else{
        
        String requette = "update motcle set mocLibelle = ? where mocLibelle = ?";
        
        try{
            PreparedStatement pstmt = maConnexion.ObtenirConnexion().prepareStatement(requette);
            pstmt.setString(1, motCleCorrige);
            pstmt.setString(2, motCleActuel);
            pstmt.executeUpdate();
            pstmt.close();
            JOptionPane.showMessageDialog(null, "Le Status du Transporteur est mis à jour");
            
            //vider la table après l'ajout
            txtMotCleActuel.setText("");
            txtMotCleCorrige.setText("");
            
        }
        catch(SQLException ex) {
            System.err.println("Erreur d'exécution de la requette:"+ ex.getErrorCode()+"/"+ ex.getMessage());
            
            }
        }
    }//GEN-LAST:event_butModifierActionPerformed

    private void butListerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butListerActionPerformed
        // TODO add your handling code here:
        //creation d'un modele
        DefaultTableModel model = new DefaultTableModel();
        
         //les colonnes
        model.addColumn("Mots Cles");
        
        //la requette
        String requette = "select * from motcle";
        
        try{
            stmtMotCle = maConnexion.ObtenirConnexion().createStatement();
            ResultSet result = stmtMotCle.executeQuery(requette);
            
            while(result.next()){
              model.addRow(new Object[]{result.getString("mocLibelle")}); 
            }
        }
        catch (SQLException ex) {
            System.err.println("Erreur d'exécution de la requette:"+ ex.getErrorCode()+"/"+ ex.getMessage());
        }
        //On applique le modele à la JTable
        tabMotsCles.setModel(model);
    }//GEN-LAST:event_butListerActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton butAjouter;
    private javax.swing.JButton butLister;
    private javax.swing.JButton butModifier;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labMotCle;
    private javax.swing.JLabel labMotCleActuel;
    private javax.swing.JLabel labMotCleCorrige;
    private javax.swing.JLabel labMotsCles;
    private javax.swing.JTable tabMotsCles;
    private javax.swing.JTextField txtMotCle;
    private javax.swing.JTextField txtMotCleActuel;
    private javax.swing.JTextField txtMotCleCorrige;
    // End of variables declaration//GEN-END:variables
}
