/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package z_tmp_view;

/**
 *
 * @author testo
 */
public class MenuFrame extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public MenuFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        RootPane = new javax.swing.JPanel();
        Right = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jButton6 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton14 = new javax.swing.JButton();
        jButton15 = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        Left = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        Top = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        Bottom = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        Center = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        RootPane.setPreferredSize(new java.awt.Dimension(600, 600));
        RootPane.setLayout(new java.awt.BorderLayout());

        Right.setPreferredSize(new java.awt.Dimension(130, 300));
        Right.setLayout(new java.awt.GridLayout(10, 0));

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Gestion Interne");
        Right.add(jLabel2);

        jButton6.setText("Livre");
        Right.add(jButton6);

        jButton8.setText("Auteur");
        Right.add(jButton8);

        jButton7.setText("Theme");
        Right.add(jButton7);

        jButton14.setText("Editeur");
        Right.add(jButton14);

        jButton15.setText("Mot-cles");
        Right.add(jButton15);

        jButton13.setText("Employe");
        Right.add(jButton13);

        jButton9.setText("Tva");
        Right.add(jButton9);

        RootPane.add(Right, java.awt.BorderLayout.LINE_END);

        Left.setPreferredSize(new java.awt.Dimension(130, 300));
        Left.setLayout(new java.awt.GridLayout(10, 0, 5, 0));

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Gestion externe");
        Left.add(jLabel4);

        jButton2.setText("Avis");
        jButton2.setMinimumSize(new java.awt.Dimension(58, 40));
        jButton2.setPreferredSize(new java.awt.Dimension(58, 35));
        Left.add(jButton2);

        jButton3.setText("Promotion");
        Left.add(jButton3);

        jButton5.setText("Commande");
        Left.add(jButton5);

        jButton4.setText("Client");
        Left.add(jButton4);

        jButton10.setText("Frais de port");
        Left.add(jButton10);

        jButton11.setText("Transporteur");
        Left.add(jButton11);

        jButton12.setText("Adresse");
        Left.add(jButton12);

        RootPane.add(Left, java.awt.BorderLayout.LINE_START);

        Top.setPreferredSize(new java.awt.Dimension(850, 60));
        Top.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Droid Sans Mono", 0, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("MENU PRINCIPAL");
        Top.add(jLabel1);
        jLabel1.setBounds(-1, 5, 750, 40);

        RootPane.add(Top, java.awt.BorderLayout.PAGE_START);

        Bottom.setPreferredSize(new java.awt.Dimension(850, 60));
        Bottom.setLayout(new java.awt.GridLayout(1, 0));

        jButton1.setText("Quitter");
        Bottom.add(jButton1);

        RootPane.add(Bottom, java.awt.BorderLayout.PAGE_END);

        Center.setLayout(null);

        jLabel3.setIcon(new javax.swing.ImageIcon("/home/kakashi/LibElec/res/backendMenu.jpg"));
        Center.add(jLabel3);
        jLabel3.setBounds(30, 0, 430, 350);

        RootPane.add(Center, java.awt.BorderLayout.CENTER);

        getContentPane().add(RootPane);
        RootPane.setBounds(0, 0, 750, 500);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new NewJFrame().setVisible(true);
//            }
//        });
//    }

   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Bottom;
    private javax.swing.JPanel Center;
    private javax.swing.JPanel Left;
    private javax.swing.JPanel Right;
    private javax.swing.JPanel RootPane;
    private javax.swing.JPanel Top;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    // End of variables declaration//GEN-END:variables
}
